return {
  Name = "NovaX Rivals",
  Version = "2026.05.13",
  Mode = "modules",
  Entry = "init.lua",
  AssetsBase = "https://raw.githubusercontent.com/y5gc8zpdwh-droid/novax-rivals-assets/main/",
  Modules = {
    "core/runtime.lua",
    "core/state.lua",
    "core/services.lua",
    "core/utils.lua",
    "core/scheduler.lua",
    "ui/NovaPremiumUI.lua",
    "combat/aimlock.lua",
    "combat/autoaim.lua",
    "combat/mouse_aim_assist.lua",
    "combat/ragebot.lua",
    "combat/triggerbot.lua",
    "combat/silent_aim.lua",
    "visual/esp.lua",
    "visual/fov.lua",
    "movement/speed.lua",
    "movement/fly.lua",
    "movement/noclip.lua",
    "movement/infjump.lua",
    "movement/antivoid.lua",
    "movement/bunnyhop.lua",
    "misc/configs.lua",
    "misc/binds.lua",
    "misc/beggerfarm.lua",
    "misc/backstab.lua",
    "misc/antihit.lua",
    "misc/control_spoof.lua",
  },
}
